spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  application:
    name: mercadolibro-service
  flyway:
    baseline-on-migrate: 'false'
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/booksdb?autoReconnect=true&useSSL=false
server:
  error:
    include-stacktrace: never
  port: 8080
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka