app:
  create-roles: ${CREATE_ROLES:false}
  roles: ${ROLES:ADMIN,USER}
  user:
    default-roles: USER
  jwt:
    secret: ${JWT_SECRET:secret}
    expiration: ${JWT_EXPIRATION:86400}
  mercadopago:
    access-token: ${MERCADOPAGO_ACCESS_TOKEN}

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
  application:
    name: ${APP_NAME:mercadolibro-service}
  flyway:
    baseline-on-migrate: 'false'
  datasource:
    password: ${DB_PASSWORD:root}
    username: ${DB_USERNAME:root}
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:booksdb}?autoReconnect=true&useSSL=false&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  error:
    include-stacktrace: never
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /v1
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

aws:
  s3:
    name: ${AWS_S3_NAME:mercadolibro-multimedia-g5}
    region: ${AWS_S3_REGION:us-east-1}
    accessKey: ${AWS_S3_ACCESS_KEY}
    secretKey: ${AWS_S3_SECRET_KEY}
    imagesPath: ${AWS_S3_IMAGES_PATH:images/}
    setUp: ${AWS_S3_SET_UP:false}

#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka