package com.mercadolibro.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;

import java.math.BigDecimal;

@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@ApiModel(description = "Payment Request DTO", value = "PaymentReqDTO")
public class PaymentReqDTO {
    @ApiModelProperty(value = "Token generated by Mercadopago SDK in the client side form (frontend)", required = true, example = "7253da25cc71ff0c4d869bb542ed4558")
    private String token;

    @JsonProperty("issuer_id")
    @ApiModelProperty(value = "It is the identifier of the card issuer being used in a credit or debit card payment.", required = true, example = "3")
    private String issuerId;

    @JsonProperty("transaction_amount")
    @ApiModelProperty(value = "Product’s cost", required = true, example = "100.5")
    private BigDecimal transactionAmount;

    @ApiModelProperty(value = "Quantity of installments", required = true, example = "1")
    private Integer installments;

    @ApiModelProperty(value = "Purchased product’s description", required = true, example = "A book")
    private String description;

    @ApiModelProperty(value = "Payer’s information", required = true)
    private Payer payer;

    @Getter
    @Setter
    @Builder
    @AllArgsConstructor
    @NoArgsConstructor
    public static class Payer {
        @JsonProperty("first_name")
        @ApiModelProperty(value = "Payer’s first name", required = true, example = "Jorge")
        private String firstName;

        @ApiModelProperty(value = "Payer’s email", required = true, example = "jorge@gmail.com")
        private String email;

        @ApiModelProperty(value = "Payer’s identification", required = true)
        private Identification identification;

        @Getter
        @Setter
        @Builder
        @AllArgsConstructor
        @NoArgsConstructor
        public static class Identification {
            @ApiModelProperty(value = "Payer’s identification type", required = true, example = "DNI, CUIT, CUIL")
            private String type;

            @ApiModelProperty(value = "Payer’s identification number", required = true, example = "12345678")
            private String number;
        }
    }
}