name: Deploy application

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar código
      uses: actions/checkout@v2

    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Generar archivo JAR
      run: mvn clean package -DskipTests
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}

    - name: Crear archivo .pem
      run: |
        echo "$SECRET_CONTENT" > secret.pem
        chmod 600 MercadoLibroKey.pem
      env:
        SECRET_CONTENT: ${{ secrets.SSH_PRIVATE_KEY }}
        

    - name: Copiar archivo JAR a instancia EC2 2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST_2 }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./target//mercadolibro-backend-1.0.0.jar"
        target: "/home/ec2-user/deploy"

    - name: Conectar a la instancia EC2
      run: ssh -i ${{ github.workspace }}/MercadoLibroKey.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST_2 }}

    - name: Establecer variables de entorno
      run: |
        export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        export DB_USERNAME=${{ secrets.DB_USERNAME }}
        export DB_HOST=${{ secrets.DB_HOST }}
        export DB_PORT=${{ secrets.DB_PORT }}
        export DB_NAME=${{ secrets.DB_NAME }}
        export SERVER_PORT=${{ secrets.SERVER_PORT }}
        echo "DB_PASSWORD=$DB_PASSWORD" >> ~/.bashrc
        echo "DB_USERNAME=$DB_USERNAME" >> ~/.bashrc
        echo "DB_HOST=$DB_HOST" >> ~/.bashrc
        echo "DB_PORT=$DB_PORT" >> ~/.bashrc
        echo "DB_NAME=$DB_NAME" >> ~/.bashrc
        echo "SERVER_PORT=$SERVER_PORT" >> ~/.bashrc
        source ~/.bashrc

    - name: Ejecutar archivo JAR en instancia EC2 2
      run: java -jar deploy/target/mercadolibro-backend-1.0.0.jar
      
    - name: Cerrar conexión SSH
      run: exit
      
